### ISSUE TITLE
Spotify album art stopped showing

### ISSUE THREAD

**Issue by drom98** [elementary/wingpanel-indicator-sound#145]
I don't really know why, but about a week ago the sound indicator stopped showing the album art from the currently playing music. But still works fine on notifications for example.

![imagem](https://user-images.githubusercontent.com/19615827/78548077-0d7b4a80-77f8-11ea-9a5b-e19daf63e681.png)

**Comment by bluesabre** [comment]
This is due to the Spotify client sending an invalid URL in mpris:artUrl

[More information](https://community.spotify.com/t5/Desktop-Linux/MPRIS-cover-art-url-file-not-found/td-p/4920104)

Invalid: https://open.spotify.com/image/ab67616d00001e02754b2fddebe7039fdb912837
Valid: https://i.scdn.co/image/ab67616d00001e02754b2fddebe7039fdb912837

**Comment by danrabbit** [comment]
As per discussion in the linked PR, I'm going to close this as "out of scope". This appears to be a (possibly temporary) issue in Spotify and not with the sound indicator
