### ISSUE TITLE
No visual feedback when changing volume on odin beta 2

### ISSUE THREAD

**Issue by Destroyer616** [elementary/wingpanel-indicator-sound#209]
## What Happened
After changing the workspace, volume indicator doesn't show any visual indicator.

## Expected Behavior

Visual indication when volume is changed

## Steps to Reproduce

1.Play a video on browser or local video player
2.Move to another workspace
3.Come back to the previous workspace and change the volume, for few seconds the volume indicator moves to the left and then
it doesn't show up thereafter until a system reboot.

## Platform
![image](https://user-images.githubusercontent.com/46772654/125023638-eb2c4880-e09c-11eb-993a-cdfbd41ff464.png)

![image](https://user-images.githubusercontent.com/46772654/125023809-3ba3a600-e09d-11eb-9fbb-6f832e68f8dc.png)

**Comment by andirsun** [comment]
I cant reproduce the issue. I am able to see the indicator no matters which workspace.

**Comment by Destroyer616** [comment]
It happens very rarely and only when i play a video on Firefox in full screen.
It doesn't happen when i use chromium or Microsoft edge
steps to reproduce:

1. Play a video on Firefox and open any messaging client, i was using google messages and signal
2. Whenever a notification comes from one of these apps or i try to change the volume the volume indicator goes to the left
3. Then disappears until the system is rebooted

**Comment by jeremypw** [comment]
Do you mean by "indicator" the scale notification that pops up while the volume is being changed?  The icon for the wingpanel sound indicator still appears to be in the wingpanel at the end of the screencast.   

Instead of rebooting you could try running `sudo killall wingpanel` in a terminal to restart the wingpanel.  Be careful not to run this command twice in succession - this will cause the wingpanel close but not restart.

After the issue occurs can you still change the volume by scrolling on the icon?

**Comment by Destroyer616** [comment]
Yes i was able to change the volume, even in the video volume changes when i was used the keyboard volume keys, but no visual notification.

**Comment by danirabbit** [comment]
This seems related to an old issue we had where notifications weren't shown on all workspaces. This should be fixed now
