### ISSUE TITLE
Change icon of unused outputs/inputs to muted variants

### ISSUE THREAD

**Issue by D0J0P** [elementary/wingpanel-indicator-sound#222]
### Problem

If you have more than one audio output/input connected and are using only one, the popover will show audio icons next to every output/input, which makes it look like they're all being used at the same time.
![Screenshot from 2021-10-19 17-35-48](https://user-images.githubusercontent.com/19495660/137994621-40958eb7-937c-4651-bdf8-019ff7e9792e.png)

(Sonata Audio is my USB DAC that my headphones are plugged into)

### Proposal

Change the audio icons of each output/input not being used to audio-volume-muted. This makes it more clear which output/input is being used, and it doesn't look like they're all being used at once.

**Comment by danrabbit** [comment]
That's a clever idea and seems like a nice little detail :)

**Comment by cassidyjames** [comment]
Oops, re-opening in case we want to address it, but I'm not sure it's an issue with the updated design.

**Comment by D0J0P** [comment]
Are there a lot of pulse icons? If not, would it be possible to make muted variants of them? They would be greyed out and slashed, as if they're turned off or not in use, making it easy to see what's used, and looks less busy.

**Comment by danrabbit** [comment]
These are device type icons, not anything specific to pulse. So it could be any device. Right now we have:
* audio-card
* audio-headphones
* audio-headset
* audio-input-microphone
* audio-speakers
* audio-subwoofer
* camera-photo
* camera-web
* computer
* computer-convertible
* computer-laptop
* phone
* video-display-tv

There might be others, but this is what seems reasonable for devices. I'm not sure it's super worth adding -muted variants for every device since we already indicate the active device with a checkmark and device icons aren't conflated with status icons here anymore

**Comment by D0J0P** [comment]
You're right, radio buttons have never had an inactive state, so it would be confusing to bring that in, making it look disabled. 

I think #226 is a good solution. Part of the confusion was probably that all outputs were using audio-volume-high, making them all look like they're on full volume, and they weren't adjustable.

**Comment by cassidyjames** [comment]
I agree with the above. If we wanted to add muted variants to all hardware types we could but I think the original problem has been resolved.
