### ISSUE TITLE
Layout jumps around when song thumbnails are loading (Spotify)

### ISSUE THREAD

**Issue by jlnr** [elementary/wingpanel-indicator-sound#60]
If I skip songs on Spotify, it apparently takes half a second to download the song thumbnail. What happens then is that the image disappears and the whole layout jumps around, then when the image finishes loading, everything jumps back to normal.

Expected behavior: The indicator's layout is stable even when the image is temporarily missing.

**Comment by peteruithoven** [comment]
Looks like this is caused by these lines: https://github.com/elementary/wingpanel-indicator-sound/blob/middleclick-mute-mic/src/Widgets/MprisGui.vala#L494-L495

The `load_remote_art` is called in rapid succession (issue 1?) with the same (valid) uri and there are errors thrown with the message "Operation was cancelled". 
The `app_icon` that's it set to in that case is `null`, looks like `app_info` isn't set for Spotify (issue 2?).
