### ISSUE TITLE
Mouse scrolling is inverted with latest commit

### ISSUE THREAD

**Issue by donadigo** [elementary/wingpanel-indicator-sound#93]
Commit https://github.com/elementary/wingpanel-indicator-sound/commit/cbf0c9ddb3eab4f391ffe65df7f32dc7d67870d4 made it so that on mouse the scrolling on the indicator is now inverted (scrolling up is volume decrease and scrolling down is volume increase).

**Comment by peteruithoven** [comment]
Some relevant discussions: https://github.com/elementary/wingpanel-indicator-sound/pull/81#issuecomment-437034545

**Comment by peteruithoven** [comment]
To summarize, the big issue is natural scrolling on Gtk.Scale's: https://gitlab.gnome.org/GNOME/gtk/issues/514
> Scrolling on a scale without Natural Scrolling enabled seems intuitive and correct: the value of the scale matches the direction of my finger movement.
> However, when enabling Natural Scrolling, I believe the scroll direction on scales is incorrectly inverted; now instead of the value matching the direction of my fingers, it goes in the opposite direction. This makes sense for scrolling content inside a scrolled view, as the metaphor has changed from controlling the scrollwheel to controlling the content itself. However, in the context of a scale, the user is still manipulating the scale itself—there is no "content" that moves inverted related to the scale.
> This has caused users of elementary OS confusion, and has required a workaround to manually invert the scroll direction in one instance, which I'd really like to avoid due to the inconsistencies with all other GtkScales.

Which is why we've inverted the direction when natural scrolling is enabled, but this leads into another big issue, we don't know whether the user is scrolling with a mouse or touchpad.
So now we're only checking the `natural-scroll` setting of `org.gnome.desktop.peripherals.touchpad` (and ignoring `org.gnome.desktop.peripherals.mouse`), as a kind of compromise. 
> it's not possible to detect whether a scroll event is coming from a touchpad or a mouse under Xorg. Therefore, having natural scroll enabled for a touchpad and then scrolling with a mouse may lead to things happening in an unexpected direction.

**Comment by jeremypw** [comment]
Using a touch pad, the volume decreases with a down stroke and increases with an up stroke, which is what I would expect.  Shouldn't scrolling down with a mouse correspond to down stroke on the keypad - or should it depend on the natural scroll setting? Is there any way to influence this relationship?

**Comment by peteruithoven** [comment]
More previous discussions: https://github.com/elementary/wingpanel-indicator-sound/pull/33

`event.device.input_source` always reports `Gdk.InputSource.MOUSE`. With mouse, touchpad, tabled pad etc. 
@donadigo adviced to try `event.get_source_device ().input_source` which does seem to work somehow. So I guess we CAN differentiate between mouse and touchpad scrolling.

**Comment by jeremypw** [comment]
It seems that you need to have the "natural scrolling" setting the same for the mouse as for the touchpad (I only just realized there are two different settings visible in the switchboard plug when you plug a mouse into a laptop.   

It does not matter what the setting is as long as they are both the same.  This is because the code is only checking one setting I think.  If they are different then you would need to know the source of the scroll event.

**Comment by peteruithoven** [comment]
Alright, with when I remove our inversion logic I get: 

mouse  pad:
  not natural: 
    vertical: makes no sense
    horizontal: makes sense
  natural: 
    vertical: makes sense
    horizontal: makes no sense
mouse:
not natural: 
  vertical: makes no sense
  horizontal: makes sense
natural: 
  vertical: makes sense
  horizontal: makes no sense

**Comment by jeremypw** [comment]
I have just pushed a PR that chooses the correct "natural-scroll" setting depending on the source of the event. It seems to work for vertical scrolling at least (I do not have a mouse with horizontal scroll capability)
